### ISSUE TITLE
Admin theme path needs updating

### ISSUE THREAD

**Issue by jools-r** [gocom/textpattern-installer#4]
In line with the recent relocation of the `/textpattern/themes` directory to `/textpattern/admin-themes`, [this line](https://github.com/gocom/textpattern-installer/blob/master/src/Textpattern/Composer/Installer/Installer/AdminTheme.php#L60) needs changing in [Installer/AdminTheme.php](https://github.com/gocom/textpattern-installer/blob/master/src/Textpattern/Composer/Installer/Installer/AdminTheme.php).

**Comment by gocom** [comment]
Has to be implemented as a conditional due to backwards compatibility, I suppose. Rule number one of programming; you don't change paths. But I guess it's too late to complain now.

**Comment by jools-r** [comment]
Cheers, thanks! Nice to see you back in action.
